SELECT E.Name, E.EmpId FROM EMPLOYEE AS E
INNER JOIN ASSIGNMENT AS A ON E.EmpId=A.EmpId
EXCEPT
SELECT E.Name, E.EmpId FROM EMPLOYEE AS E
INNER JOIN ASSIGNMENT AS A ON E.EmpId=A.EmpId
WHERE strftime('%Y', StartDate) = '2011'
ORDER BY E.Name